# Generated by Django 5.0.6 on 2026-05-11 08:00

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=20, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("initialization", "Initialization"),
                            ("recommendation", "Recommendation"),
                            ("consolidation", "Consolidation"),
                            ("pre_assignment", "Pre-Assignment"),
                            ("validation", "Validation"),
                            ("closed", "Closed"),
                        ],
                        default="initialization",
                        max_length=30,
                        protected=True,
                    ),
                ),
                ("wishes_open_date", models.DateField(blank=True, null=True)),
                ("wishes_close_date", models.DateField(blank=True, null=True)),
                ("gpa_freeze_date", models.DateField(blank=True, null=True)),
                (
                    "results_publication_date",
                    models.DateField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
                "ordering": ["-start_date"],
            },
        ),
    ]
