# Generated by Django 5.0.6 on 2026-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0002_academicyear_closed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
