# Generated by Django 5.2.13 on 2026-07-06 08:09

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0006_update_campaign_status_fsm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("initialization", "Initialisation"),
                    ("recommendation", "Recommandation"),
                    ("candidature", "Candidature"),
                    ("import", "Import"),
                    ("pre_assignment", "Pré-affectation"),
                    ("validation", "Validation"),
                    ("published", "Publiée"),
                    ("closed", "Clôturée"),
                ],
                default="initialization",
                max_length=30,
                protected=True,
            ),
        ),
    ]
