# Generated by Django 5.2.13 on 2026-07-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outgoing", "0004_add_override_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentresult",
            name="system_note",
            field=models.CharField(
                blank=True,
                help_text="Explication automatique pour un cas particulier (ex. vœux incompatibles avec le niveau d'études).",
                max_length=255,
                verbose_name="Remarque système",
            ),
        ),
    ]
