[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
pythonpath = .
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore::UserWarning:django.core.handlers.base
    ignore::django.utils.deprecation.RemovedInDjango61Warning:ninja