# Generated by Django 5.2.13 on 2026-07-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cti", "0002_remove_meets_cti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mobilityduration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
