# Generated by Django 5.0.6 on 2026-05-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerUniversity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moveon_id",
                    models.IntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=100)),
                ("translated_name", models.CharField(blank=True, max_length=255)),
                ("erasmus_code", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("last_sync_moveon", models.DateTimeField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="universities",
                        to="reference.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner University",
                "verbose_name_plural": "Partner Universities",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["moveon_id"], name="institutio_moveon__6ba91b_idx"
                    ),
                    models.Index(
                        fields=["country"], name="institutio_country_cae0e5_idx"
                    ),
                ],
            },
        ),
    ]
