# Generated by Django 5.0.6 on 2026-05-08 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="partneruniversity",
            new_name="institution_moveon__3f8703_idx",
            old_name="institutio_moveon__6ba91b_idx",
        ),
        migrations.RenameIndex(
            model_name="partneruniversity",
            new_name="institution_country_b8f71c_idx",
            old_name="institutio_country_cae0e5_idx",
        ),
    ]
