# Generated by Django 5.0.6 on 2026-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0003_partneruniversityrawimport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partneruniversity",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="partneruniversityrawimport",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
