# Generated by Django 5.0.6 on 2026-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0005_audit_fields"),
        ("reference", "0009_merge_0008_audit_fields_0008_drop_rawimport_tables"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="partneruniversity",
            index=models.Index(fields=["name"], name="univ_name_idx"),
        ),
        migrations.AddIndex(
            model_name="partneruniversity",
            index=models.Index(fields=["erasmus_code"], name="univ_erasmus_idx"),
        ),
    ]
