# Generated by Django 5.2.13 on 2026-08-26 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0007_partneruniversityrawimportstatus_conflict"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partneruniversity",
            options={
                "ordering": ["name", "id"],
                "verbose_name": "Partner University",
                "verbose_name_plural": "Partner Universities",
            },
        ),
    ]
