# Generated by Django 5.0.6 on 2026-05-11 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0001_initial"),
        (
            "institutions",
            "0002_rename_institutio_moveon__6ba91b_idx_institution_moveon__3f8703_idx_and_more",
        ),
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "moveon_relation_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("relation_type", models.CharField(blank=True, max_length=100)),
                ("framework", models.CharField(blank=True, max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("outgoing", "Outgoing"),
                            ("incoming", "Incoming"),
                            ("both", "Both"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("start_academic_year", models.CharField(blank=True, max_length=20)),
                ("end_academic_year", models.CharField(blank=True, max_length=20)),
                ("discipline", models.CharField(blank=True, max_length=255)),
                ("isced", models.CharField(blank=True, max_length=100)),
                ("level", models.CharField(blank=True, max_length=100)),
                ("formation", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True)),
                ("restrictions", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                ("last_sync_moveon", models.DateTimeField(blank=True, null=True)),
                (
                    "partner_university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreements",
                        to="institutions.partneruniversity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agreement",
                "verbose_name_plural": "Agreements",
                "ordering": ["partner_university__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="AgreementQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_year_label", models.CharField(max_length=20)),
                ("period", models.CharField(blank=True, max_length=100)),
                (
                    "places_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("total_places", models.PositiveSmallIntegerField(default=0)),
                ("remaining_places", models.PositiveSmallIntegerField(default=0)),
                (
                    "total_duration",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("duration_unit", models.CharField(blank=True, max_length=50)),
                ("is_effective", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_quotas",
                        to="academic.academicyear",
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotas",
                        to="mobility.agreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agreement Quota",
                "verbose_name_plural": "Agreement Quotas",
                "ordering": [
                    "-academic_year_label",
                    "agreement__partner_university__name",
                ],
            },
        ),
        migrations.CreateModel(
            name="DepartmentQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("places", models.PositiveSmallIntegerField(default=0)),
                ("remarks", models.TextField(blank=True)),
                (
                    "agreement_quota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_quotas",
                        to="mobility.agreementquota",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_quotas",
                        to="reference.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department Quota",
                "verbose_name_plural": "Department Quotas",
                "ordering": ["agreement_quota", "department__code"],
            },
        ),
        migrations.CreateModel(
            name="RawImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=100)),
                ("source_file", models.CharField(blank=True, max_length=255)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Raw Import",
                "verbose_name_plural": "Raw Imports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "external_id"],
                        name="mobility_ra_source_80cef3_idx",
                    ),
                    models.Index(
                        fields=["status"], name="mobility_ra_status_6e1223_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["moveon_relation_id"], name="mobility_ag_moveon__6c946d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["partner_university"], name="mobility_ag_partner_75236c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(fields=["status"], name="mobility_ag_status_3e1a44_idx"),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["is_active"], name="mobility_ag_is_acti_50e465_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agreementquota",
            index=models.Index(
                fields=["agreement"], name="mobility_ag_agreeme_29ed21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agreementquota",
            index=models.Index(
                fields=["academic_year"], name="mobility_ag_academi_3cd492_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agreementquota",
            index=models.Index(
                fields=["academic_year_label"], name="mobility_ag_academi_d000e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agreementquota",
            index=models.Index(
                fields=["places_id"], name="mobility_ag_places__2c81b6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="agreementquota",
            constraint=models.UniqueConstraint(
                fields=("agreement", "academic_year_label", "period"),
                name="unique_agreement_quota_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentquota",
            constraint=models.UniqueConstraint(
                fields=("agreement_quota", "department"), name="unique_department_quota"
            ),
        ),
    ]
