# Generated by Django 5.0.6 on 2026-05-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0001_initial"),
        (
            "institutions",
            "0002_rename_institutio_moveon__6ba91b_idx_institution_moveon__3f8703_idx_and_more",
        ),
        ("mobility", "0001_initial"),
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreement",
            options={
                "ordering": ["name"],
                "verbose_name": "Agreement",
                "verbose_name_plural": "Agreements",
            },
        ),
        migrations.AlterModelOptions(
            name="agreementquota",
            options={
                "ordering": ["academic_year_label"],
                "verbose_name": "Agreement Quota",
                "verbose_name_plural": "Agreement Quotas",
            },
        ),
        migrations.AlterModelOptions(
            name="departmentquota",
            options={
                "ordering": ["department"],
                "verbose_name": "Department Quota",
                "verbose_name_plural": "Department Quotas",
            },
        ),
        migrations.RemoveConstraint(
            model_name="agreementquota",
            name="unique_agreement_quota_period",
        ),
        migrations.RemoveConstraint(
            model_name="departmentquota",
            name="unique_department_quota",
        ),
        migrations.RemoveIndex(
            model_name="agreement",
            name="mobility_ag_moveon__6c946d_idx",
        ),
        migrations.RemoveIndex(
            model_name="agreement",
            name="mobility_ag_partner_75236c_idx",
        ),
        migrations.RemoveIndex(
            model_name="agreement",
            name="mobility_ag_is_acti_50e465_idx",
        ),
        migrations.RemoveIndex(
            model_name="agreementquota",
            name="mobility_ag_agreeme_29ed21_idx",
        ),
        migrations.RemoveIndex(
            model_name="agreementquota",
            name="mobility_ag_academi_3cd492_idx",
        ),
        migrations.RemoveIndex(
            model_name="agreementquota",
            name="mobility_ag_academi_d000e0_idx",
        ),
        migrations.RemoveIndex(
            model_name="agreementquota",
            name="mobility_ag_places__2c81b6_idx",
        ),
        migrations.AlterField(
            model_name="agreement",
            name="direction",
            field=models.CharField(default="unknown", max_length=50),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="isced",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="moveon_relation_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="reference",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="status",
            field=models.CharField(default="draft", max_length=50),
        ),
        migrations.AlterField(
            model_name="agreementquota",
            name="places_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="agreementquota",
            name="remaining_places",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="agreementquota",
            name="total_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agreementquota",
            name="total_places",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="departmentquota",
            name="places",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="rawimport",
            name="external_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rawimport",
            name="source",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="departmentquota",
            unique_together={("agreement_quota", "department")},
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["partner_university", "is_active"],
                name="mobility_ag_partner_a6a955_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agreementquota",
            index=models.Index(
                fields=["agreement", "academic_year"],
                name="mobility_ag_agreeme_e20b2e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentquota",
            index=models.Index(
                fields=["agreement_quota", "department"],
                name="mobility_de_agreeme_8b2721_idx",
            ),
        ),
    ]
