# Generated by ChatGPT on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobility", "0005_agreementquota_source_places"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="mobility_type",
            field=models.CharField(default="unknown", max_length=50),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["mobility_type", "direction"],
                name="mobility_ag_mobilit_48f60c_idx",
            ),
        ),
    ]
