# Generated by ChatGPT on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobility", "0006_agreement_mobility_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgreementFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("moveon_framework_id", models.CharField(max_length=255, unique=True)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("relation_types", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_moveon", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Agreement Framework",
                "verbose_name_plural": "Agreement Frameworks",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="agreement",
            name="framework_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="agreements",
                to="mobility.agreementframework",
            ),
        ),
        migrations.AddIndex(
            model_name="agreementframework",
            index=models.Index(
                fields=["moveon_framework_id"],
                name="mobility_ag_moveon__10bae2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agreementframework",
            index=models.Index(fields=["name"], name="mobility_ag_name_33c781_idx"),
        ),
        migrations.AddIndex(
            model_name="agreementframework",
            index=models.Index(
                fields=["is_active"],
                name="mobility_ag_is_acti_9bfe0b_idx",
            ),
        ),
    ]
