# Generated by ChatGPT on 2026-05-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0001_initial"),
        ("mobility", "0007_agreement_framework"),
        ("reference", "0002_pegase_department_imports"),
    ]

    operations = [
        migrations.CreateModel(
            name="MobilityLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Mobility Level",
                "verbose_name_plural": "Mobility Levels",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AgreementYearAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("academic_year_label", models.CharField(max_length=20)),
                ("is_available", models.BooleanField(default=True)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("remarks", models.TextField(blank=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_availabilities",
                        to="academic.academicyear",
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_availabilities",
                        to="mobility.agreement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agreement Year Availability",
                "verbose_name_plural": "Agreement Year Availabilities",
                "ordering": ["academic_year_label", "agreement__name"],
            },
        ),
        migrations.CreateModel(
            name="AgreementDepartmentConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("remarks", models.TextField(blank=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_constraints",
                        to="mobility.agreement",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_constraints",
                        to="reference.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agreement Department Constraint",
                "verbose_name_plural": "Agreement Department Constraints",
                "ordering": ["agreement__name", "department__code"],
            },
        ),
        migrations.CreateModel(
            name="AgreementLevelConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("source", models.CharField(default="manual", max_length=50)),
                ("remarks", models.TextField(blank=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="level_constraints",
                        to="mobility.agreement",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreement_constraints",
                        to="mobility.mobilitylevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agreement Level Constraint",
                "verbose_name_plural": "Agreement Level Constraints",
                "ordering": ["agreement__name", "level__code"],
            },
        ),
        migrations.AddIndex(
            model_name="mobilitylevel",
            index=models.Index(fields=["code"], name="mobility_mo_code_ee9c52_idx"),
        ),
        migrations.AddIndex(
            model_name="mobilitylevel",
            index=models.Index(
                fields=["is_active"], name="mobility_mo_is_acti_a2fc51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agreementyearavailability",
            index=models.Index(
                fields=["academic_year_label", "is_available"],
                name="mobility_ag_academi_458e93_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agreementyearavailability",
            index=models.Index(
                fields=["agreement", "academic_year"],
                name="mobility_ag_agreeme_e3b175_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreementyearavailability",
            constraint=models.UniqueConstraint(
                fields=("agreement", "academic_year_label"),
                name="unique_agreement_year_availability",
            ),
        ),
        migrations.AddIndex(
            model_name="agreementdepartmentconstraint",
            index=models.Index(
                fields=["agreement", "is_active"],
                name="mobility_ag_agreeme_e95e57_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agreementdepartmentconstraint",
            index=models.Index(
                fields=["department", "is_active"],
                name="mobility_ag_departm_b5d8ac_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreementdepartmentconstraint",
            constraint=models.UniqueConstraint(
                fields=("agreement", "department"),
                name="unique_agreement_department_constraint",
            ),
        ),
        migrations.AddIndex(
            model_name="agreementlevelconstraint",
            index=models.Index(
                fields=["agreement", "is_active"],
                name="mobility_ag_agreeme_047638_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agreementlevelconstraint",
            index=models.Index(
                fields=["level", "is_active"],
                name="mobility_ag_level_i_b056e7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreementlevelconstraint",
            constraint=models.UniqueConstraint(
                fields=("agreement", "level"),
                name="unique_agreement_level_constraint",
            ),
        ),
    ]
