# Generated by ChatGPT on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobility", "0008_agreement_constraints_availability_levels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawimport",
            name="entity",
            field=models.CharField(
                choices=[
                    ("partner_university", "Partner University"),
                    ("agreement_framework", "Agreement Framework"),
                    ("agreement", "Agreement"),
                    ("agreement_availability", "Agreement Availability"),
                    ("agreement_department", "Agreement Department"),
                    ("agreement_level", "Agreement Level"),
                    ("agreement_quota", "Agreement Quota"),
                    ("department_quota", "Department Quota"),
                    ("mobility_level", "Mobility Level"),
                ],
                default="partner_university",
                max_length=50,
            ),
        ),
    ]
