# Generated by Django 5.0.6 on 2026-05-28 09:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mobility", "0018_remove_agreement_mobility_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mobilitycategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Mobility Category",
                "verbose_name_plural": "Mobility Categories",
            },
        ),
        migrations.RenameIndex(
            model_name="mobilitycategory",
            new_name="mobility_mo_moveon__c7e278_idx",
            old_name="mobility_ag_moveon__10bae2_idx",
        ),
        migrations.RenameIndex(
            model_name="mobilitycategory",
            new_name="mobility_mo_name_ff68fb_idx",
            old_name="mobility_ag_name_33c781_idx",
        ),
        migrations.RenameIndex(
            model_name="mobilitycategory",
            new_name="mobility_mo_is_acti_00d4ad_idx",
            old_name="mobility_ag_is_acti_9bfe0b_idx",
        ),
    ]
