# Generated by Django 5.0.6 on 2026-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobility", "0019_alter_mobilitycategory_options_and_more"),
        ("reference", "0006_parcours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agreementlevelconstraint",
            name="agreement",
        ),
        migrations.RemoveField(
            model_name="agreementlevelconstraint",
            name="level",
        ),
        migrations.RemoveField(
            model_name="agreementyearavailability",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="agreementyearavailability",
            name="source",
        ),
        migrations.AddField(
            model_name="agreement",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="agreements", to="reference.department"
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="levels",
            field=models.ManyToManyField(
                blank=True, related_name="agreements", to="reference.level"
            ),
        ),
        migrations.DeleteModel(
            name="AgreementDepartmentConstraint",
        ),
        migrations.DeleteModel(
            name="AgreementLevelConstraint",
        ),
    ]
