# Generated by Django 5.0.6 on 2026-05-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobility", "0021_rename_framework_to_category"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mobilitycategory",
            name="mobility_mo_moveon__c7e278_idx",
        ),
        migrations.AddIndex(
            model_name="mobilitycategory",
            index=models.Index(
                fields=["moveon_id"], name="mobility_mo_moveon__6c4197_idx"
            ),
        ),
    ]
