# Generated by Django 5.0.6 on 2026-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobility", "0025_rename_moveon_relation_id_to_moveon_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="agreementquota",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="agreementyearavailability",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="departmentquota",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mobilitycategory",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="rawimport",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
