# Generated by Django 5.0.6 on 2026-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0002_academicyear_closed_at"),
        ("mobility", "0026_alter_agreement_id_alter_agreementquota_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreementquota",
            options={
                "ordering": ["academic_year__label"],
                "verbose_name": "Agreement Quota",
                "verbose_name_plural": "Agreement Quotas",
            },
        ),
        migrations.AlterModelOptions(
            name="agreementyearavailability",
            options={
                "ordering": ["academic_year__label", "agreement__name"],
                "verbose_name": "Agreement Year Availability",
                "verbose_name_plural": "Agreement Year Availabilities",
            },
        ),
        migrations.RemoveConstraint(
            model_name="agreementquota",
            name="unique_agreement_quota_period",
        ),
        migrations.RemoveConstraint(
            model_name="agreementyearavailability",
            name="unique_agreement_year_availability",
        ),
        migrations.RemoveIndex(
            model_name="agreementyearavailability",
            name="mobility_ag_academi_458e93_idx",
        ),
        migrations.RemoveField(
            model_name="agreementquota",
            name="academic_year_label",
        ),
        migrations.RemoveField(
            model_name="agreementyearavailability",
            name="academic_year_label",
        ),
        migrations.AddConstraint(
            model_name="agreementquota",
            constraint=models.UniqueConstraint(
                fields=("agreement", "academic_year", "period"),
                name="unique_agreement_quota_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="agreementyearavailability",
            constraint=models.UniqueConstraint(
                fields=("agreement", "academic_year"),
                name="unique_agreement_year_availability",
            ),
        ),
    ]
