# Generated by Django 5.0.6 on 2026-06-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobility", "0030_drop_rawimport"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mobilitycategory",
            options={
                "ordering": ["name"],
                "verbose_name": "Cadre de mobilité",
                "verbose_name_plural": "Cadres de mobilité",
            },
        ),
        migrations.RemoveIndex(
            model_name="mobilitycategory",
            name="mobility_mo_is_acti_00d4ad_idx",
        ),
        migrations.RenameIndex(
            model_name="agreement",
            new_name="mobility_ag_partner_75236c_idx",
            old_name="mobility_agreement_partner_idx",
        ),
        migrations.RenameIndex(
            model_name="agreementyear",
            new_name="mobility_ag_agreeme_02955f_idx",
            old_name="mobility_agreementyear_idx",
        ),
        migrations.RenameIndex(
            model_name="agreementyear",
            new_name="mobility_ag_is_acti_b6a6ca_idx",
            old_name="mobility_agreementyear_active_idx",
        ),
        migrations.RenameIndex(
            model_name="agreementyeardepartment",
            new_name="mobility_ag_agreeme_0ad96d_idx",
            old_name="mobility_agrdept_idx",
        ),
        migrations.RemoveField(
            model_name="mobilitycategory",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="mobilitycategory",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="mobilitycategory",
            name="relation_types",
        ),
        migrations.AlterField(
            model_name="mobilitycategory",
            name="moveon_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
