# Generated by Django 5.0.6 on 2026-06-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0004_audit_fields"),
        ("mobility", "0035_agreementyeardepartment_use_agreementdepartment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreementyeardepartment",
            options={
                "ordering": ["agreement_department__department__code"],
                "verbose_name": "Agreement Year Department",
                "verbose_name_plural": "Agreement Year Departments",
            },
        ),
        migrations.RenameIndex(
            model_name="agreementdepartment",
            new_name="mobility_ag_agreeme_9e305e_idx",
            old_name="mobility_ag_agreeme_dept_idx",
        ),
        migrations.RenameIndex(
            model_name="agreementyeardepartment",
            new_name="mobility_ag_agreeme_ea4670_idx",
            old_name="mobility_ag_agreeme_ayd_idx",
        ),
        migrations.AddIndex(
            model_name="agreementyear",
            index=models.Index(
                fields=["academic_year"], name="mobility_agrmt_year_idx"
            ),
        ),
    ]
