# Generated by Django 5.0.6 on 2026-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0006_partneruniversity_univ_name_idx_and_more"),
        ("mobility", "0036_add_agreement_year_academic_year_index"),
        ("reference", "0009_merge_0008_audit_fields_0008_drop_rawimport_tables"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(fields=["name"], name="agreement_name_idx"),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["partner_university", "name"], name="agreement_univ_name_idx"
            ),
        ),
    ]
