# Generated by Django 5.2.13 on 2026-08-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institutions", "0007_partneruniversityrawimportstatus_conflict"),
        ("mobility", "0042_agreementyear_duration_months"),
        ("reference", "0011_level_is_terminal"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Suppression douce : l'accord n'est plus actif à partir de maintenant (plus d'instance future) mais son historique dans les années déjà closes reste intact.",
                null=True,
                verbose_name="Supprimé le",
            ),
        ),
        migrations.AddIndex(
            model_name="agreement",
            index=models.Index(
                fields=["deleted_at"], name="mobility_ag_deleted_d55280_idx"
            ),
        ),
    ]
