# Generated by Django 5.2.13 on 2026-08-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mobility", "0043_agreement_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="duration_weeks",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Durée standard du séjour, reprise comme valeur par défaut pour chaque nouvelle instance annuelle de cet accord (modifiable ensuite instance par instance).",
                null=True,
                verbose_name="Durée (semaines)",
            ),
        ),
    ]
