# Generated by Django 5.2.13 on 2026-08-26 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mobility", "0044_agreement_duration_weeks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreement",
            options={
                "ordering": ["name", "id"],
                "verbose_name": "Agreement",
                "verbose_name_plural": "Agreements",
            },
        ),
        migrations.AlterModelOptions(
            name="agreementyear",
            options={
                "ordering": ["-academic_year__label", "agreement__name", "id"],
                "verbose_name": "Agreement Year",
                "verbose_name_plural": "Agreement Years",
            },
        ),
        migrations.AlterModelOptions(
            name="agreementyeardepartment",
            options={
                "ordering": ["agreement_department__department__code", "id"],
                "verbose_name": "Agreement Year Department",
                "verbose_name_plural": "Agreement Year Departments",
            },
        ),
    ]
