# Generated by Django 5.0.6 on 2026-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_remove_student_pegase_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualenrollment",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
