# Generated by Django 5.0.6 on 2026-06-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0004_audit_fields"),
        ("reference", "0009_merge_0008_audit_fields_0008_drop_rawimport_tables"),
        ("students", "0009_studentwish_use_annual_enrollment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentwish",
            options={
                "ordering": [
                    "annual_enrollment__student__last_name",
                    "annual_enrollment__academic_year__start_date",
                    "rank",
                ],
                "verbose_name": "Vœu étudiant",
                "verbose_name_plural": "Vœux étudiants",
            },
        ),
        migrations.AddIndex(
            model_name="annualenrollment",
            index=models.Index(
                fields=["academic_year"], name="students_enroll_year_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annualenrollment",
            index=models.Index(
                fields=["academic_year", "student"], name="students_enroll_year_stu_idx"
            ),
        ),
    ]
