# Generated by Django 5.0.6 on 2026-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0004_audit_fields"),
        ("reference", "0009_merge_0008_audit_fields_0008_drop_rawimport_tables"),
        ("students", "0010_add_academic_year_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="annualenrollment",
            index=models.Index(
                fields=["academic_year", "department"],
                name="students_enroll_year_dept_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="annualenrollment",
            index=models.Index(
                fields=["academic_year", "level"], name="students_enroll_year_level_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annualenrollment",
            index=models.Index(
                fields=["academic_year", "parcours"], name="enroll_year_parcours_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["last_name", "first_name"], name="student_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["last_name"], name="student_last_name_idx"),
        ),
    ]
