# Generated by Django 5.0.6 on 2026-06-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0011_annualenrollment_students_enroll_year_dept_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualenrollment",
            name="last_sync_pegase",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière sync Pégase"
            ),
        ),
        migrations.AddField(
            model_name="studentwish",
            name="last_sync_moveon",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière sync MoveOn"
            ),
        ),
    ]
