# Generated by Django 5.2.13 on 2026-08-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0008_add_finalization_status"),
        ("reference", "0011_level_is_terminal"),
        ("students", "0020_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualenrollment",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Suppression douce : l'inscription n'apparaît plus dans la liste par défaut, mais reste consultable dans l'historique et peut être restaurée.",
                null=True,
                verbose_name="Supprimée le",
            ),
        ),
        migrations.AddIndex(
            model_name="annualenrollment",
            index=models.Index(
                fields=["deleted_at"], name="students_enroll_deleted_idx"
            ),
        ),
    ]
