# Generated by Django 5.2.13 on 2026-07-20 13:54

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0007_alter_academicyear_status"),
        ("reference", "0010_parcours_unique_together_to_constraint"),
        ("students", "0017_assignment_add_created_updated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplementaryMobility",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "experience_type",
                    models.CharField(
                        help_text="Ex : Summer school, séjour linguistique, programme court…",
                        max_length=100,
                        verbose_name="Type d'expérience",
                    ),
                ),
                (
                    "destination_institution",
                    models.CharField(blank=True, max_length=255),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "document_key",
                    models.CharField(
                        blank=True,
                        help_text="Clé objet MinIO du justificatif déposé",
                        max_length=512,
                    ),
                ),
                ("document_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("pending", "En attente de validation"),
                            ("validated", "Validée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=20,
                        protected=True,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complementary_mobilities",
                        to="academic.academicyear",
                    ),
                ),
                (
                    "destination_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complementary_mobilities",
                        to="reference.country",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complementary_mobilities",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobilité complémentaire",
                "verbose_name_plural": "Mobilités complémentaires",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["student"], name="compl_mob_student_idx"),
                    models.Index(fields=["status"], name="compl_mob_status_idx"),
                    models.Index(fields=["academic_year"], name="compl_mob_year_idx"),
                ],
            },
        ),
    ]
