# Generated by Django 5.0.6 on 2026-05-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2, unique=True, verbose_name='Code ISO 3166-1 alpha-2')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom en francais')),
                ('name_en', models.CharField(max_length=100, verbose_name='Nom en anglais')),
                ('cti_region', models.CharField(choices=[('france', 'France'), ('europe_hors_france', 'Europe (hors France)'), ('canada_usa', 'Canada / États-Unis'), ('amerique', "Autres pays d'Amérique"), ('asie_moyen_orient', 'Asie / Moyen-Orient'), ('afrique', 'Afrique'), ('oceanie', 'Océanie')], max_length=20, verbose_name='Region CTI')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code departement')),
                ('name', models.CharField(max_length=100, verbose_name='Intitule')),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
                'ordering': ['code'],
            },
        ),
    ]
