# Generated by Django 5.0.6 on 2026-05-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference", "0004_copy_level_data"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="level",
            new_name="reference_l_code_906c70_idx",
            old_name="reference_l_code_idx",
        ),
        migrations.RenameIndex(
            model_name="level",
            new_name="reference_l_is_acti_1a5854_idx",
            old_name="reference_l_is_acti_idx",
        ),
        migrations.RenameIndex(
            model_name="levelrawimport",
            new_name="reference_l_source_af075b_idx",
            old_name="reference_l_source_extid_idx",
        ),
        migrations.RenameIndex(
            model_name="levelrawimport",
            new_name="reference_l_status_0811af_idx",
            old_name="reference_l_status_idx",
        ),
        migrations.AlterField(
            model_name="level",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="levelrawimport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
