# Generated by Django 5.0.6 on 2026-05-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reference",
            "0005_rename_reference_l_code_idx_reference_l_code_906c70_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("label", models.CharField(max_length=100)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcours_list",
                        to="reference.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parcours",
                "verbose_name_plural": "Parcours",
                "ordering": ["department", "code"],
                "unique_together": {("department", "code")},
            },
        ),
    ]
