# Generated by Django 5.0.6 on 2026-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference", "0006_parcours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="departmentrawimport",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="level",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="levelrawimport",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="parcours",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
