# Generated by Django 5.0.6 on 2026-06-05 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reference", "0008_audit_fields"),
        ("reference", "0008_drop_rawimport_tables"),
    ]

    operations = []
