# Generated by Django 5.0.6 on 2026-06-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0004_rawimportentity_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="importreport",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="importreport",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="rawimport",
            name="created_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="rawimport",
            name="updated_by",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
