# Generated by Django 5.0.6 on 2026-06-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "0004_audit_fields"),
        ("imports", "0005_audit_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rawimport",
            index=models.Index(fields=["academic_year"], name="imports_raw_year_idx"),
        ),
        migrations.AddIndex(
            model_name="rawimport",
            index=models.Index(
                fields=["academic_year", "status"], name="imports_raw_year_status_idx"
            ),
        ),
    ]
