# Generated by Django 5.2.13 on 2026-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0009_alter_importreport_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawimport",
            name="entity",
            field=models.CharField(
                choices=[
                    ("department", "Département"),
                    ("level", "Niveau"),
                    ("partner_university", "Université partenaire"),
                    ("agreement_category", "Catégorie d'accord"),
                    ("agreement", "Accord"),
                    ("student", "Étudiant"),
                    ("internship", "Stage"),
                    ("incoming_student", "Étudiant entrant"),
                ],
                max_length=50,
            ),
        ),
    ]
