# Generated by Django 5.2.13 on 2026-07-06 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academic", "0007_alter_academicyear_status"),
        ("reference", "0010_parcours_unique_together_to_constraint"),
        ("students", "0017_assignment_add_created_updated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="Internship",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Raison sociale"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=255, verbose_name="Ville"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=500, verbose_name="Titre"),
                ),
                (
                    "internship_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Type de stage"
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Code statut"
                    ),
                ),
                (
                    "status_label",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Libellé statut"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                (
                    "weeks_in_company",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Nb semaines entreprise"
                    ),
                ),
                (
                    "school_tutor",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Tuteur pédagogique"
                    ),
                ),
                (
                    "company_tutor",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Tuteur technique entreprise",
                    ),
                ),
                (
                    "eudonet_label",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Libellé Eudonet"
                    ),
                ),
                (
                    "last_sync_eudonet",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière sync Eudonet"
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internships",
                        to="academic.academicyear",
                        verbose_name="Année universitaire",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="internships",
                        to="reference.country",
                        verbose_name="Pays",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="internships",
                        to="students.student",
                        verbose_name="Étudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stage",
                "verbose_name_plural": "Stages",
                "ordering": ["-start_date", "student__last_name"],
                "indexes": [
                    models.Index(fields=["student"], name="internship_student_idx"),
                    models.Index(fields=["academic_year"], name="internship_year_idx"),
                    models.Index(fields=["country"], name="internship_country_idx"),
                    models.Index(
                        fields=["start_date"], name="internship_start_date_idx"
                    ),
                ],
                "unique_together": {("student", "company_name", "start_date")},
            },
        ),
    ]
